language: c
sudo: true

matrix:
  include:
    - compiler: gcc
      env: MAKECMDS="make && make distcheck"
    - compiler: clang
    - compiler: gcc-5
      env: CC=gcc-5 COVERAGE=t ARGS="--enable-code-coverage" MAKECMDS="make && make check-code-coverage && lcov -l flux*-coverage.info"
    - compiler: gcc-7
      env: CC=gcc-7
    - compiler: clang-4.0
      env: CC=clang-4.0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - gcc-5
      - gcc-7
      - clang-4.0
      - lcov
      - libjansson-dev

before_install:
  - curl -L -O --insecure https://github.com/jedisct1/libsodium/releases/download/1.0.10/libsodium-1.0.10.tar.gz
  - tar -xf libsodium-1.0.10.tar.gz
  - (cd libsodium-1.0.10 && ./configure --prefix=$HOME/local && make && make install)
  - curl -L -O --insecure https://github.com/dun/munge/releases/download/munge-0.5.13/munge-0.5.13.tar.xz
  - tar -xJf munge-0.5.13.tar.xz
  - (cd munge-0.5.13 && ./configure --prefix=$HOME/local && make && make install)
  - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$HOME/local/share/pkgconfig
  - PATH=$HOME/local/bin:$HOME/local/sbin:$PATH

script:
  - export FLUX_TESTS_LOGFILE=t
  # Force update to allow version m4 to work
  - ( git fetch --unshallow --tags || true )
  - ./autogen.sh
  - ./configure ${ARGS}
  - eval ${MAKECMDS:-make && make check}

after_success:
  - if test "$COVERAGE" = "t"; then bash <(curl -s https://codecov.io/bash); fi

after_failure:
  - find . -name t[0-9]*.output | xargs -i sh -c 'printf "\033[31mFound {}\033[39m\n";cat {}'

before_deploy:
  # Get anchor (formatted properly) and base URI for latest tag in NEWS file
  - export ANCHOR=$(sed -n '/^flux-security version/{s/\.//g; s/\s/-/gp;Q}' NEWS.md)
  - export TAG_URI="https://github.com/${TRAVIS_REPO_SLUG}/blob/${TRAVIS_TAG}"
  - export TARBALL=$(echo flux-security*.tar.gz)
  - ls -l $TARBALL
  - echo "Deploying tag ${TRAVIS_TAG} as $TARBALL"

deploy:
  provider: releases
  skip_cleanup: true
  file: $TARBALL
  prerelease: true
  body: "View [Release Notes](${TAG_URI}/NEWS.md#${ANCHOR}) for flux-security ${TRAVIS_TAG}"
  on:
    # Only deploy from first job in build matrix
    condition: $TRAVIS_JOB_NUMBER = $TRAVIS_BUILD_NUMBER.1
    tags: true
    repo: grondo/flux-security
  api_key:
    secure: G0TyfiblXI0QXPCyU+Hq9OGaYGqli63qtCtfnaHABGagnfcDOhSjcNV626en89oOaHu+uoa8t3Izo7i7/1vfGTil3Sj1mko5/XpZwdF3wh7hySwWdAtrT59a1k3vLyMT79NWUDGHDhnQvh5b1lHYBBjSh95t6gPiMkhjB+x2pkLMfeR1D5Nhhy1o1ELoulz3+wl+MlNBJga1RDYAkT9nZFI9JDJgw+bDHzACHp2y+GMIWLrFsXgXW3s8NLY8EJPDKm1QTK+kqVnenJENx9/lqvwZ3GkCl1HBjrQSyITjMoX5sYp9ikTBJvAI937er8GzF86Fi76OoduV3yCHh93TnWhugqIhVPfcK9niGlVm3bEIDeugFszf9gp1ja9sQ3+WRe9Kind8ThFY/X3Wp9bN89meZMSs6t/r/78+ypURpkG2ZB0ACk2alIdx5d/d0wFNurjHIcczygVMnhMEEgQO72T6t13pTuKc8/MwvJUki9gdSIiTwqqx/xgQ7142Ou2cb8pTWmy4PKc3HjZfmnBCZpu1gosQ+DnZbSGTUENCKFrGqFzlj+INt2banctWPQ15qRAmZ3vnu7Ekc+yRvZue1IBQWQCsbwKPxlqqFVbIOB+sW2o5wx52dGVfpP1t5Slut3bnsyJepQjSnTiHNrVyemEwpBTHIVeIuMo/9u3MjgE=
