on: [ pull_request, push ]
jobs:
  check-pr:
    name: validate commits
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - run: git fetch origin master
    - uses: flux-framework/pr-validator@master

  generate-matrix:
    # https://stackoverflow.com/questions/59977364
    name: Generate build matrix
    runs-on: ubuntu-latest
    outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - id: set-matrix
      run: echo "::set-output name=matrix::$(src/test/generate-matrix.py)"
    - run: src/test/generate-matrix.py | jq -S .
    - run: echo "::set-output name=GITHUB_BRANCH::${GITHUB_REF#refs/heads}"
    - run: echo "::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags}"
    - run: echo "::set-output name=EVENT_NAME::${{github.event_name}}"
  
  ci:
    needs: [ generate-matrix ]
    runs-on: ubuntu-latest
    env:
      FLUX_TESTS_LOGFILE: t
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    name: ${{ matrix.name }}
    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: fetch annotated tag
      if: matrix.create_release
      run: |
        # Ensure git-describe works on a tag.
        #  (checkout@v2 action may have left current tag as
        #   lightweight instead of annotated. See
        #   https://github.com/actions/checkout/issues/290)
        #
        echo github.ref == ${{ github.ref }} ;
        git fetch -f origin ${{ github.ref }}:${{ github.ref }} ;
        echo git describe now reports $(git describe --always)

    - name: docker buildx
      uses: docker/setup-buildx-action@v1
      if: matrix.needs_buildx

    - name: docker-run-checks
      env: ${{matrix.env}}
      run: ${{matrix.command}}

    - name: annotate errors
      if: failure() || cancelled()
      env: ${{matrix.env}}
      run: src/test/checks-annotate.sh

    - name: coverage report
      if: success() && matrix.coverage
      uses: codecov/codecov-action@v1

    - name: prep release
      id: prep_release
      if: success() && matrix.create_release
      run: echo "::set-output name=tarball::$(echo flux-security*.tar.tz)"

    - name: create release
      id: create_release
      if: success() && matrix.create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: flux-security ${{ github.ref }}
        prerelease: true
        body: >
          View [Release Notes](https://github.com/${{ github.repository }}/blob/${{ github.ref }}/NEWS.md) for flux-security ${{ github.ref }}

    - name: upload tarball
      id: upload-tarball
      if: success() && matrix.create_release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.prep_release.outputs.tarball }}
        asset_name: ${{ steps.prep_release.outputs.tarball }}
        asset_content_type: "application/gzip"

